[package]
name = "dioxus-icons-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
heck = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
svg = "0.18.0"
walkdir = "2.5.0"
